### ISSUE TITLE
"Error occured while checking the submission. Evaluation error: object 'python_grade_result' not found."

### ISSUE THREAD

**Issue by DrMondesire** [rstudio/pygradethis#39]
When running the rscript.R demo file, I receive the following error:

_"Error occurred while checking the submission. Evaluation error: object 'python_grade_result' not found."_

Following the [wiki](https://github.com/rstudio/pygradethis/wiki/Development-Guide/0f9b5396f079f07600840c32244960ac62f80545): I am running Ubuntu 18.03, python 3.10.3, compiled pygradethis from this github repo, and the python demo works. The compilation from the _pygradethis/python_ folder worked when I changed the MakeFile's python calls to python3. The _pygradethis/R_ compilation did **not** work and returned the following error:

```
rm -f pygradethis_*.tar.gz
rm -rf pygradethis.Rcheck
R CMD build .
* checking for file ‘./DESCRIPTION’ ... OK
* preparing ‘pygradethis’:
* checking DESCRIPTION meta-information ... OK
* checking for LF line-endings in source and make files and shell scripts
* checking for empty or unneeded directories
Omitted ‘LazyData’ from DESCRIPTION
* building ‘pygradethis_0.0.0.9000.tar.gz’

R CMD INSTALL pygradethis_0.0.0.9000.tar.gz
* installing to library ‘/usr/local/lib/R/site-library’
ERROR: dependency ‘reticulate’ is not available for package ‘pygradethis’
* removing ‘/usr/local/lib/R/site-library/pygradethis’
make: *** [Makefile:17: install] Error 1
```

Also, I updated the rscript.R file to point to my system's "~/.virtualenvs/pygradethis" instead of the demo's default virtual environment path:
`reticulate::use_virtualenv("~/.venvs/pygradethis")`

**Comment by chendaniely** [comment]
Hi @DrMondesire this seems like an installation + setup issue. Thanks for letting us know!

- In the R installation process, it looks like the `reticulate` R package isn't installed to communicate with python.
- I also created issue #40 for us to keep track of, thank you for bringing that to our attention.

Since this repository is _very_ work in progress there are a lot of things that are broken as we fix up the connections between R and Python along with the python code grading mechanisms.

At the moment I'll have to close this issue since we're doing very fast iterations of things, and nothing we say in issues will be ephemeral.
